# Generated by Django 5.1.6 on 2025-03-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JQuestions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_res',
            new_name='questionRes',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='questionText',
        ),
        migrations.AddField(
            model_name='question',
            name='curEpisode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='curSeason',
            field=models.IntegerField(default=0),
        ),
    ]
