# Generated by Django 5.1.6 on 2025-03-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JQuestions', '0002_rename_question_res_question_questionres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='curEpisode',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='curSeason',
            field=models.IntegerField(default=1),
        ),
    ]
