# Generated by Django 5.1.6 on 2025-03-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JQuestions', '0003_alter_question_curepisode_alter_question_curseason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionRes',
            field=models.TextField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionText',
            field=models.TextField(max_length=400, unique=True),
        ),
    ]
