# Generated by Django 5.1.6 on 2025-03-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JQuestions', '0004_alter_question_questionres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionRes',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionText',
            field=models.TextField(max_length=400),
        ),
    ]
